server:
    port: 8081
spring:
  datasource:
    url: jdbc:mysql://123.206.225.210:3306/daigou_admin?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    tomcat:
      max-idle: 50

# MyBatis
mybatis:
  typeAliasesPackage: com.mugen.admin.model
#  mapperLocations: classpath:/com/ddb/**/domain/*.xml
  mapper-locations: classpath:/mapper/*.xml

thrift:
  server:
   port: 7911

services:
  - name: userService
    classpath: com.mugen.admin.thriftint.UserService
    maxThreads: 50
  - name: userService1
    classpath: com.mugen.admin.thriftint.UserService1
    maxThreads: 50
zookeeper:
  server:
    list: 123.206.225.210:2181


