server:
    port: 8082
service:
  name: userService

spring:
  datasource:
    url: jdbc:mysql://123.206.225.210:3306/daigou_admin?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    tomcat:
      max-idle: 50

zookeeper:
  server:
    list: 123.206.225.210:2181


